// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using RizSoft.Blazor.Models;

#nullable disable

namespace RizSoft.Blazor.Data
{
    public partial class AcmeDbContext : Microsoft.EntityFrameworkCore.DbContext
    {
        public AcmeDbContext()
        {
        }

        public AcmeDbContext(DbContextOptions<AcmeDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Category>(entity =>
            {
                entity.Property(e => e.CategoryId)
                    .HasColumnType("int")
                    .ValueGeneratedNever();

                entity.Property(e => e.CategoryName)
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");
            });

            modelBuilder.Entity<Product>(entity =>
            {
                entity.Property(e => e.ProductId)
                    .HasColumnType("int")
                    .ValueGeneratedNever();

                entity.Property(e => e.CategoryId).HasColumnType("int");

                entity.Property(e => e.Price)
                    .IsRequired()
                    .HasColumnType("money");

                entity.Property(e => e.ProductName)
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.Products)
                    .HasForeignKey(d => d.CategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}